steps:
- name: 'gcr.io/cloud-builders/bazel'
  args: ['build', '--jobs=4','--remote_cache=https://storage.googleapis.com/negainoido-icfpc2019-bazel-cache', '//...']
- name: 'gcr.io/cloud-builders/bazel'
  args: ['test', '--jobs=4', '--remote_cache=https://storage.googleapis.com/negainoido-icfpc2019-bazel-cache', '//...']
- name: 'gcr.io/cloud-builders/bazel'
  args: ['help', 'build']
  waitFor: ['-']
