cc_binary(
    name = "flowlight_solver",
    srcs = ["main.cc"],
    deps = [
        "//base",
        "//base:ai",
        "//base:flags",
        "//base:graph",
        "@com_google_glog//:glog",
    ],
)
