cc_binary(
    name = "flowlight_solver",
    srcs = ["flowlight_solver.cc"],
    deps = [
        "//base:graph",
        "//flowlight/main:common",
        "@com_google_glog//:glog",
    ],              
)

